#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

run:
  concurrency: 4
  timeout: 3m
  issues-exit-code: 1
  tests: true
  build-tags: [""]

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt:.*
      - io/ioutil:^Read.*
  govet:
    enable:
      - shadow
  revive:
    confidence: 0.6
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 500
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    # default locale is a neutral variety of English.
    locale:
    ignore-words: []
  lll:
    line-length: 120
    tab-width: 1
  unused:
    exported-fields-are-used: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 0
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
    disabled-checks:
      - unnamedResult
      - whyNoLint # TODO enable.
  funlen:
    lines: 60
    statements: 40
  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    force-case-trailing-whitespace: 0
    allow-cuddle-declarations: false
  godot:
    check-all: false
  predeclared:
    ignore: "min,max,clear"

linters:
  enable-all: true
  disable:
    - gomoddirectives
    - nolintlint
    - varnamelen
    - tenv
    - tagliatelle
    - testpackage
    - prealloc
    - exhaustive #TODO enable
    - goerr113 # TODO enable
    - nlreturn # TODO enable
    - noctx # TODO enable
    - paralleltest
    - tparallel
    - cyclop # TODO consider replacing gocyclo with cyclop
    - makezero # TODO enable
    - wrapcheck # TODO enable
    - thelper # TODO enable
    - usestdlibvars
    - testableexamples
    - stylecheck
    - gci
    - staticcheck
    - nonamedreturns
    - nilnil
    - ireturn
    - mnd
    - gosimple
    - errchkjson
    - errname
    - dupword
    - interfacebloat
    - forcetypeassert
    - exhaustruct
    - contextcheck
    - containedctx
    - bodyclose
    - gosec
    - gofumpt
    - gofmt
    - gocritic
    - goimports
    - gocognit
    - forbidigo
    - nosprintfhostport
    - typecheck
    - maintidx
    - depguard
    - musttag
    - mirror
    - errorlint
    - nakedret
    - recvcheck
    - testifylint
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - mnd
        - maintidx
        - usestdlibvars
        - testableexamples
        - stylecheck
        - typecheck
        - maintidx
        - mirror
        - lll
        - goconst
        - wsl
        - errcheck
        - perfsprint
    - path: example_[^\/]*_test\.go
      linters:
        - dupl
        - funlen
        - mnd
        - goconst
        - lll
    - source: "swagger:route"
      linters:
        - lll

  exclude:
    # Allow package logger variables (for now)
    - logger is a global variable
    # Add comments for package
    - at least one file in a package should have a package comment
    - Line contains TODO/BUG/FIXME
    # Allow magic number 1
    - Magic number[:] 1[^\d]
    # Temporarily allow old protobuf reference
    - package github.com/golang/protobuf/proto is deprecated
