#
# Copyright Gen Digital Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: "vc-go ci"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  SemanticPullRequest:
    name: Semantic Pull Request Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Checks:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run checks
        run: |
          echo $PATH
          go env
          echo ${{ github.workspace }}
          make checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  UnitTest:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:

      - name: Setup Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
        id: go

      - uses: actions/checkout@v3

      - name: Run unit test
        timeout-minutes: 15
        run: make unit-test

      - name: Upload coverage to Codecov
        timeout-minutes: 10
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.out